EBook/Models/Books/Author/AuthorListViewModel.cs
using EBook.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EBook.Models
{
    public class AuthorListViewModel
    {
        public List<Author> Authors { get; set; }       
    }
}

EBook/Models/Books/Book/BookListViewModel.cs
using EBook.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EBook.Models
{
    public class BookListViewModel
    {
        public PageInfo pageInfo { get; set; }
        public List<Book> Books { get; set; }           
    }
}

EBook/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EBook.Models;
using EBook.Business.Abstract;
using EBook.Entity;

namespace EBook.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private IBookService _bookServices;
        private IAuthorServices _authorServices;

        public HomeController(ILogger<HomeController> logger, IBookService bookService, IAuthorServices authorServices)
        {
            _logger = logger;
            _bookServices = bookService;
            _authorServices = authorServices;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult BookList(string category,int page=1)
        {
            const int pagesize = 2;
            var BookViewModel = new BookListViewModel()
            {
                pageInfo = new PageInfo()
                {
                    TotalItems = _bookServices.GetCountByCategory(category),
                    CurrentPage = page,
                    ItemsPerPage = pagesize,
                    CurrentCategory = category
                },
                Books = _bookServices.GetBooksByCategory(category, page, pagesize)
            };

            return View(BookViewModel);
        }

        public IActionResult BookDetails(string Url)
        {
            Book book = _bookServices.GetBookDetails(Url);
            var tut = book.BookCategories.Select(i=>i.Categories).FirstOrDefault();
            var getbooks = _bookServices.GetCategoryBook(tut);
            ViewBag.BookCategory = getbooks;
            return View(new BookDetailModel()
            {
                Book = book,
                Category=book.BookCategories.Select(i=>i.Categories).ToList(),
                Author=book.BookAuthors.Select(i=>i.Author).FirstOrDefault()
            });
        }
        /* şuan burası pasif 
        public IActionResult BookRead(int id)
        {
            Book book = _bookService.GetBookReadDetails(id);

            return View(new BookDetailModel()
            {
                Book = book,
                Category = book.BookCategories.Select(i => i.Categories).ToList()

            });
        } */

        public IActionResult AuthorList()
        {
            AuthorListViewModel authorListViewModel = new AuthorListViewModel()//şurayı sor () olmadanda çalışıyor neden?
            {
                Authors = _authorServices.GetAll()
            };
            return View(authorListViewModel);
        }
        public IActionResult AuthorDetail(string Yurl)           
        {   
            Author author = _authorServices.GetAuthorDetails(Yurl);
            return View(new AuthorDetailModel { 
            Author=author,
            Books=author.BookAuthors.Select(i=>i.Book).ToList()
            });
        }






















        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EBook/ViewComponents/BookMiddleViewComponent.cs
using EBook.Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EBook.ViewComponents
{
    public class BookMiddleViewComponent:ViewComponent
    {
        private IBookService _bookService;
        public BookMiddleViewComponent(IBookService bookService)
        {
            _bookService = bookService;
        }

        public IViewComponentResult Invoke()
        {
            var model = new EBook.Models.BookListViewModel
            {
                pageInfo=null,
                Books = _bookService.GetAllMiddle()
            };
            return View(model);
        }
    }
}

EBook/ViewComponents/CategoriesViewComponent.cs
using EBook.Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EBook.ViewComponents
{
    public class CategoriesViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoriesViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["category"] != null)
                ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(_categoryService.GetAll());
        }
    }
}

EBook/Views/Home/AuthorDetail.cshtml
@model AuthorDetailModel

<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="@Model.Author.Image" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.Author.NameSurname</h5>
        <p class="card-text">@Model.Author.Description</p>
        <hr />
    </div>
    <ul class="list-group list-group-flush">
        <p class="card-text">@Model.Author.Content</p>
        <li class="list-group-item">Dapibus ac facilisis in</li>
        <li class="list-group-item">Vestibulum at eros</li>
    </ul>
    <div class="card-body">

        @foreach (var item in Model.Books)
        {
            <div class="card mb-2">
                <img class="card-img-top" src="@item.Image" alt="">
                <div class="card-body">
                    <h5 class="card-title">@item.BookName</h5>
                    <small class="text-muted">
                        <i class="fas fa-lira-sing"><h5>Sayfa Sayısı</h5> @item.Pages</i>
                    </small>
                </div>
                <div class="card-footer text-center">
                    <a asp-controller="Home" asp-action="BookDetails" asp-route-Url="@item.Url" class="btn btn-primary btn-sm">İncele</a> @*book details altındaki product bilgisine gidiyo giderkende productid gönderiyo biz id bilgisini alıyoruz ve o id bilgisine uyan kaydı book comtroller içerisinde kullanıcılara göstericez*@
                </div>
            </div>
        }


    </div>
</div>

EBook/Views/Home/AuthorList.cshtml
@model AuthorListViewModel

@foreach (var item in Model.Authors)
{

    @await Html.PartialAsync("_AuthorList", item)

}

EBook/Views/Home/BookDetails.cshtml
@model BookDetailModel


<div class="card mb-3 mt-3">
    <div class="card-body">
        <div class="row no-gutter">
            <div class="col-md-3">
                <img src="@Model.Book.Image" class="card-img" alt="">
            </div>
            <div class="col-md-9">
                <h5 class="car-title">@Model.Book.BookName</h5>
                <h6 class="card-text">@Model.Book.Pages</h6>

                @foreach (var item in Model.Category)
                {
                    <a asp-controller="home" asp-action="booklist" asp-route-category="@item.Url" class="btn btn-link p-0 mb-3">@item.Tittle</a>
                }
                <hr>
                <a  class="btn btn-primary btn-sm">@Model.Author.NameSurname</a> @*book details altındaki product bilgisine gidiyo giderkende productid gönderiyo biz id bilgisini alıyoruz ve o id bilgisine uyan kaydı book comtroller içerisinde kullanıcılara göstericez*@
                <p class="card-text">@Model.Book.Description</p>
                <a asp-controller="Home" asp-action="BookRead" asp-route-id="@Model.Book.BookId" class="btn btn-primary btn-sm">Oku</a> @*book details altındaki product bilgisine gidiyo giderkende productid gönderiyo biz id bilgisini alıyoruz ve o id bilgisine uyan kaydı book comtroller içerisinde kullanıcılara göstericez*@
            </div>
        </div>
    </div>
</div>

<hr />

<div class="card-deck">
    <div class="card">
        @foreach (var item in (List<Book>)ViewBag.BookCategory)
        {
            <img src="@item.Image" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">@item.BookName</h5>
                <p class="card-text">@item.Description</p>
            </div>
            
        }
    </div>
</div>

EBook/Views/Home/BookList.cshtml
@model BookListViewModel


<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
    </div>
    @await Component.InvokeAsync("BookMiddle")

    <div class="col-md-9">
        @foreach (var item in Model.Books)
        {
            @await Html.PartialAsync("_BookList", item)
        }
    </div>
</div>


                    <div class="row">
                        <div class="col">
                            <nav aria-label="Page navigation example">
                                <ul class="pagination">
                                    <a class="page-link" href="/kitap?page=@(1)">Ana Sayfa</a>
                                    @for (int i = 0; i < Model.pageInfo.TotalPages(); i++)
                                    {
                                        @if(string.IsNullOrEmpty(Model.pageInfo.CurrentCategory))//kategori dolumu boşmu
                                        {
                                            <li class="page-item @(Model.pageInfo.CurrentPage==i+1?"active":"")">@*o an hangi sayfa gösteriliyorsa o sayı i+1 e eşitse aktif olsun buton değilse pasif*@
                                                <a class="page-link" href="/kitap?page=@(i+1)">@*controllerden page verilirse giderse ve zaten i+1 artacak oda eşitse buna basınca 1,2 ye gider*@
                                                @(i+1) @*ekranda gösterilecek*@
                                                </a>
                                           </li>
                                        }
                                        else
                                        {
                                             <li class="page-item @(Model.pageInfo.CurrentPage==i+1?"active":"")">
                                                <a class="page-link" href="/kitap/@Model.pageInfo.CurrentCategory?page=@(i+1)">
                                                @(i+1)
                                                </a>
                                           </li>
                                        }
                                        
                                    }
                                    
                                </ul>
                            </nav>
                        </div>
                    </div>
        </div>      
    </div>
</div>

EBook/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
     